export type UsageState =
  | 'default'
  | 'lowBalance'
  | 'exhausted'
  | 'paymentFailed'
  | 'cancelling'
  | 'loading'
  | 'emptyHistory'
  | 'withBreakdown'
  | 'withoutBreakdown'
  | 'changePlanStudio'
  | 'changePlanCatalog'
  | 'changePlanStorefront'
  | 'changePlanSent'
  | 'changePlanFailed'
  | 'changePlanNarrow'
  | 'noPlan'
  | 'noPlanModal'
  | 'noPlanChosen'
  | 'noPlanFailed'
  | 'noPlanNarrow'
  | 'cancelVerify'
  | 'cancelCode'
  | 'cancelWrongCode'
  | 'cancelExpiredCode'
  | 'cancelConsequences'
  | 'cancelSmallerPlan'
  | 'cancelSmallest'
  | 'cancelReason'
  | 'cancelReasonOther'
  | 'cancelConfirm'
  | 'cancelSubmitting'
  | 'cancelDone'
  | 'cancelFailed'
  | 'error';

export const focusRing =
  'focus:outline-none focus-visible:ring-2 focus-visible:ring-[var(--focus)] focus-visible:ring-offset-2 focus-visible:ring-offset-[var(--canvas)]';

export type PlanStatus = 'active' | 'cancelling';

export interface Plan {
  name: string;
  status: PlanStatus;
  price: number;
  interval: string;
  billingPeriod: string;
  includedRenders: number;
  renewalDate: string;
  cancelDate: string;
  startDate: string;
  nextBillingDate: string;
}

export const planData: Plan = {
  name: 'Starter',
  status: 'active',
  price: 149,
  interval: 'per month',
  billingPeriod: '12 Mar – 12 Apr 2026',
  includedRenders: 300,
  renewalDate: '12 April 2026',
  cancelDate: '12 April 2026',
  startDate: '12 March 2026',
  nextBillingDate: '12 April 2026',
};

export interface Balance {
  allowanceUsed: number;
  allowanceTotal: number;
  allowanceRemaining: number;
  topUpRemaining: number;
  topUpPacks: number;
}

const balanceDefault: Balance = {
  allowanceUsed: 134,
  allowanceTotal: 300,
  allowanceRemaining: 166,
  topUpRemaining: 40,
  topUpPacks: 2,
};

export function getBalance(state: UsageState): Balance {
  if (state === 'lowBalance')
    return {
      allowanceUsed: 252,
      allowanceTotal: 300,
      allowanceRemaining: 48,
      topUpRemaining: 40,
      topUpPacks: 2,
    };
  if (state === 'exhausted')
    return {
      allowanceUsed: 300,
      allowanceTotal: 300,
      allowanceRemaining: 0,
      topUpRemaining: 0,
      topUpPacks: 0,
    };
  return balanceDefault;
}

export interface ConsumptionRow {
  cause: string;
  subline: string;
  count: number;
  highlighted?: boolean;
}

export const consumptionData: ConsumptionRow[] = [
  { cause: 'Custom design generation', subline: 'Bespoke designs you generated', count: 48 },
  { cause: 'Design refinement', subline: 'Views you asked to be redone', count: 22 },
  { cause: 'Product ingestion', subline: 'New products added to a catalog', count: 18 },
  { cause: 'Repair passes', subline: "Automatic corrections when a render didn't match your photograph", count: 21 },
  { cause: 'Re-uploads', subline: 'Products regenerated after you replaced photographs', count: 11 },
  { cause: 'Color extensions', subline: 'Existing products generated in a color you added later', count: 8 },
  { cause: 'Widget generation', subline: 'Designs generated by visitors on your website', count: 6 },
];

export interface TopUpPack {
  size: number;
  price: number;
  pricePerCredit: number;
  validity: string;
  bestValue?: boolean;
}

export const topUpPacksData: TopUpPack[] = [
  { size: 25, price: 20, pricePerCredit: 0.8, validity: '120 Days Validity' },
  { size: 50, price: 35, pricePerCredit: 0.7, validity: '180 Days Validity' },
  { size: 100, price: 60, pricePerCredit: 0.6, validity: '365 Days Validity', bestValue: true },
];

export interface Purchase {
  date: string;
  pack: number;
  remaining: number;
  paid: number;
}

export const purchasesData: Purchase[] = [
  { date: '2 April 2026', pack: 50, remaining: 18, paid: 35 },
  { date: '18 March 2026', pack: 50, remaining: 22, paid: 35 },
];

export interface Invoice {
  reference: string;
  date: string;
  amount: number;
  status: 'Paid' | 'Failed';
}

export const invoicesData: Invoice[] = [
  { reference: 'INV-0042', date: '12 March 2026', amount: 149, status: 'Paid' },
  { reference: 'INV-0041', date: '12 February 2026', amount: 149, status: 'Paid' },
  { reference: 'INV-0040', date: '12 January 2026', amount: 149, status: 'Paid' },
  { reference: 'INV-0035', date: '12 December 2025', amount: 149, status: 'Paid' },
  { reference: 'INV-0031', date: '12 November 2025', amount: 149, status: 'Paid' },
  { reference: 'INV-0027', date: '12 October 2025', amount: 149, status: 'Paid' },
];

export interface CancelInfo {
  accessUntil: string;
  bullets: string[];
}

export const cancelInfo: CancelInfo = {
  accessUntil: '12 April 2026',
  bullets: [
    'Every published catalog is unpublished. Share links stop working.',
    'The widget stops generating on your website.',
    'Your remaining base allowance expires — 166 renders.',
    'Your remaining top-up packs expire too — 40 renders.',
  ],
};

export const planLimits: string[] = [
  'Render usage is never stored in your plan.',
  'Unused renders do not roll over into the next period.',
  'Top-up renders are consumed only after your base plan allowance runs out.',
];

export interface BillingActivity {
  pendingLabel: string;
  paymentMethod: string;
  cardLast4: string;
  activityTitle: string;
  activityCount: number;
  activitySubtitle: string;
}

export const billingActivityData: BillingActivity = {
  pendingLabel: 'Pending',
  paymentMethod: 'Subscription is paid using Debit Card, Visa',
  cardLast4: '2102',
  activityTitle: 'All your billing activity',
  activityCount: 10,
  activitySubtitle: 'Invoice receipts and payment records.',
};

export interface ActivityEvent {
  icon: string;
  event: string;
  description: string;
  at: string;
  status: string;
  tone: 'success' | 'neutral';
}

export const activityEventsData: ActivityEvent[] = [
  {
    icon: 'ri-image-add-line',
    event: 'Render generated',
    description: 'A new product image was generated from your photograph.',
    at: '8 April 2026, 09:41',
    status: 'Completed',
    tone: 'success',
  },
  {
    icon: 'ri-share-forward-line',
    event: 'Design shared with customer',
    description: 'A design link was sent to a customer for approval.',
    at: '6 April 2026, 14:20',
    status: 'Sent',
    tone: 'neutral',
  },
  {
    icon: 'ri-checkbox-circle-line',
    event: 'Customer approved design',
    description: 'A customer approved the design you sent them.',
    at: '5 April 2026, 11:05',
    status: 'Approved',
    tone: 'success',
  },
  {
    icon: 'ri-file-list-3-line',
    event: 'Manufacturer quote sent',
    description: 'Your request was sent to a manufacturer for a quote.',
    at: '4 April 2026, 09:41',
    status: 'Sent',
    tone: 'neutral',
  },
  {
    icon: 'ri-add-circle-line',
    event: 'Additional render pack added',
    description: 'A 50-render top-up pack was added to your balance.',
    at: '2 April 2026, 16:02',
    status: 'Completed',
    tone: 'success',
  },
  {
    icon: 'ri-refresh-line',
    event: 'Subscription renewed',
    description: 'Your Starter plan renewed for another billing period.',
    at: '12 March 2026, 08:00',
    status: 'Completed',
    tone: 'success',
  },
];